name: "Hello World"
description: "Greet someone and record the time"
inputs:
  who-to-greet: # id of input
    description: "Who to greet"
    required: true
    default: "World"

  label:
    description: "Optional label"
    required: false

outputs:
  time: # id of output
    description: "The time we greeted you"

runs:
  using: "node20"
  main: "index.js"
