name: "Hello World"
description: "Greet someone and record the time"
inputs:
  label:
    description: "Optional label"
    required: false
  filePath:
    description: "File path of the project info (e.g: package.json) relative to the root directory of the repository."
    required: true
  repoToken:
    description: GitHub repository token
    required: true

outputs:
  time: # id of output
    description: "The time we greeted you"

runs:
  using: "node20"
  main: "index.js"
