name: Test Action

on: [push]

jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Hello world action step
        uses: ./
        id: hello
        with:
          who-to-greet: "John"

      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
