name: Test Action

on: [push]

jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Hello world action step
        uses: ./github/actions/action
        id: hello
        with:
          who-to-greet: "John"

      - name: Print the greeting's output
        run: echo "The greeting was ${{ steps.hello.outputs.greeting }}"
